server:
  error:
    include-stacktrace: ON_PARAM

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anime
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: Spring Boot 2 Essentials by DevDojo
  website: https://devdojo.academy
  githut: https://github.com/devdojobr/springboot2-essentials
